package bcwadsworth.devices.resources;

import net.minecraft.block.Block;
import net.minecraft.item.Item;
import bcwadsworth.devices.blocks.BlockGemOre;
import bcwadsworth.devices.blocks.BlockImperfectOre;
import bcwadsworth.devices.items.ItemCircuit;
import bcwadsworth.devices.items.ItemGem;
import bcwadsworth.devices.items.ItemMatrix;
import bcwadsworth.devices.items.tools.ToolHoe;
import bcwadsworth.devices.items.tools.ToolPickaxe;
import bcwadsworth.devices.items.tools.ToolShovel;
import bcwadsworth.devices.items.tools.ToolSword;

public class ORef
{
	public static ItemGem gemRed;
	public static ItemGem gemEnd;
	public static ItemGem gemGlow;
	public static ItemGem gemQuartz;
	public static ItemCircuit circuitCapacitative;
	public static ItemCircuit circuitComputational;
	public static ItemCircuit circuitEnergetic;
	public static ItemCircuit circuitRandom;
	public static ItemCircuit circuitTransforming;
	public static ItemCircuit circuitVoid;
	public static ItemMatrix matrixRandom;
	public static ItemMatrix matrixStorage;
	public static Item toolTransformBlock;
	public static Item toolVoidBlock;
	public static Item toolVoidBlockRanged;
	public static Item toolVoidItem;
	public static Item toolVoidItemWhite;
	public static Item toolVoidItemBlack;
	public static Item toolVoidTile;
	public static ToolPickaxe pickaxeGemRed;
	public static ToolPickaxe pickaxeGemEnd;
	public static ToolPickaxe pickaxeGemDiamond;
	public static ToolPickaxe pickaxeGemEmerald;
	public static ToolPickaxe pickaxeGemQuartz;
	public static ToolPickaxe pickaxeGemGlow;
	public static ToolPickaxe pickaxeLapis;
	public static ToolPickaxe pickaxeObsidian;
	public static ToolHoe axeGemRed;
	public static ToolHoe axeGemEnd;
	public static ToolHoe axeGemDiamond;
	public static ToolHoe axeGemEmerald;
	public static ToolHoe axeGemQuartz;
	public static ToolHoe axeGemGlow;
	public static ToolHoe axeLapis;
	public static ToolHoe axeObsidian;
	public static ToolShovel shovelGemRed;
	public static ToolShovel shovelGemEnd;
	public static ToolShovel shovelGemDiamond;
	public static ToolShovel shovelGemEmerald;
	public static ToolShovel shovelGemQuartz;
	public static ToolShovel shovelGemGlow;
	public static ToolShovel shovelLapis;
	public static ToolShovel shovelObsidian;
	public static ToolSword swordGemRed;
	public static ToolSword swordGemEnd;
	public static ToolSword swordGemDiamond;
	public static ToolSword swordGemEmerald;
	public static ToolSword swordGemQuartz;
	public static ToolSword swordGemGlow;
	public static ToolSword swordLapis;
	public static ToolSword swordObsidian;
	public static ToolHoe hoeGemRed;
	public static ToolHoe hoeGemEnd;
	public static ToolHoe hoeGemDiamond;
	public static ToolHoe hoeGemEmerald;
	public static ToolHoe hoeGemQuartz;
	public static ToolHoe hoeGemGlow;
	public static ToolHoe hoeLapis;
	public static ToolHoe hoeObsidian;
	
	public static BlockGemOre oreGemRed;
	public static BlockGemOre oreGemEnd;
	public static BlockGemOre oreGemDiamond;
	public static BlockGemOre oreGemEmerald;
	public static BlockGemOre oreGemQuartz;
	public static BlockGemOre oreGemGlow;
	public static BlockImperfectOre oreImperfectDiamond;
	public static Block fuelEnrichedCoal;
}
